'use strict';
const assert = require('assert');
const { describeRequest, logRequestDiagnostic } = require('../api_request_diagnostic');
const base = 'http://hidden:password@example.test/api?token=secret&key=wrong&nro_tel_from=5493462612530';
const report = describeRequest('PEV4', base);
assert.equal(report.endpoint, 'http://example.test/api');
assert.deepEqual(report.nro_tel_from, ['5493462612530']);
assert.equal(report.key_matches_expected, false);
assert.equal(report.key_present, true);
assert.equal(describeRequest('SDG', base), null);
assert.equal(describeRequest('PEV4', 'http://example.test').key_present, false);
assert.equal(describeRequest('PEV4', base + '&key=another').key_count, 2);
const output = [];
logRequestDiagnostic('PEV4', base, s => output.push(s), 1000);
logRequestDiagnostic('PEV4', base, s => output.push(s), 2000);
assert.equal(output.length, 1);
logRequestDiagnostic('PEV4', base, s => output.push(s), 61000);
assert.equal(output.length, 2);
logRequestDiagnostic('PEV4', base.replace('5493462612530', '123'), s => output.push(s), 62000);
assert.equal(output.length, 3);
logRequestDiagnostic('PEV4', 'invalid', s => output.push(s));
assert.equal(output.length, 3);
for (const secret of ['hidden', 'password', 'secret', 'wrong']) assert(!output.join('').includes(secret));
console.log('API request diagnostic tests passed');
