'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const { applyFastForward, createMultiUpdateWatcher } = require('../safe_agent_update');
(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'asisto-update-test-'));
  const git = (...args) => execFileSync('git', args, { cwd: dir, encoding: 'utf8', stdio: ['ignore','pipe','pipe'] }).trim();
  git('init'); git('config','user.email','test@example.invalid'); git('config','user.name','Test');
  fs.writeFileSync(path.join(dir,'app.js'),'old'); fs.writeFileSync(path.join(dir,'package-lock.json'),'original');
  git('add','.'); git('commit','-m','base'); const base = git('rev-parse','HEAD');
  fs.writeFileSync(path.join(dir,'app.js'),'new'); git('add','app.js'); git('commit','-m','release');
  const target = git('rev-parse','HEAD'); git('switch','--detach',base);
  fs.writeFileSync(path.join(dir,'package-lock.json'),'customer lock');
  fs.writeFileSync(path.join(dir,'configuracion.json.bak'),'customer config');
  const run = async (cmd,args) => ({ stdout: execFileSync(cmd,args,{cwd:dir,encoding:'utf8',stdio:['ignore','pipe','pipe']}) });
  await applyFastForward(run,dir,target);
  assert.equal(git('rev-parse','HEAD'),target);
  assert.equal(fs.readFileSync(path.join(dir,'package-lock.json'),'utf8'),'customer lock');
  assert.equal(fs.readFileSync(path.join(dir,'configuracion.json.bak'),'utf8'),'customer config');
  git('switch','--detach',base); fs.writeFileSync(path.join(dir,'app.js'),'customer edit');
  await assert.rejects(applyFastForward(run,dir,target));
  assert.equal(git('rev-parse','HEAD'),base);
  assert.equal(fs.readFileSync(path.join(dir,'app.js'),'utf8'),'customer edit');
  const calls=[]; const watch=createMultiUpdateWatcher('v4.05.29');
  const opts={enabled:true,primary:true,target:'v4.05.30',restart:async t=>calls.push(t)};
  assert.equal(await watch({...opts,primary:false}),false);
  assert.equal(await watch({...opts,enabled:false}),false);
  assert.equal(await watch({...opts,target:'v4.05.29'}),false);
  assert.equal(await watch(opts),true); assert.equal(await watch(opts),false);
  assert.deepEqual(calls,['v4.05.30']);
  const failed=createMultiUpdateWatcher('v4.05.29');
  await assert.rejects(failed({...opts,restart:async()=>{throw Error('ipc');}}));
  assert.equal(await failed(opts),true);
  console.log('safe_agent_update: OK; preserved test fixture at '+dir);
})().catch(e=>{console.error(e);process.exitCode=1;});
